version: '3.9'

services:
  app:
    container_name: todo-api
    hostname: todo-api
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=development